design_system:
  # Components directory
  components:
    # Location of your components directory
    directory: components
    # CSS compiler (if applicable) (sass)
    css_compiler: sass
    # Entry Point
    styles_entrypoint: components/index.scss
    
