design_system:
  
  # Location of your components directory
  directory: /components
  
  # CSS compiler (css, sass)
  css_compiler: sass
  
  # CSS Entry Point
  styles_entrypoint: components/index.scss
  
  # Components
  components:
    - buttons
    - typography
    
