design_system:
  
  # Location of your components directory
  directory: /components
  
  # CSS compiler (css, sass)
  css_compiler: sass
  
  # CSS Entry Point
  styles_entrypoint: components/index.scss
  
  # JS Entry Point
  js_entrypoint: components/index.js
  
  # Components
  components:
    - buttons
    - typography
    
