# These settings are used by Design System

# Sugguested Folder Structure
# components/
#   buttons/
#       buttons.scss
#       buttons.md

# Components directory
components:
    # Location of your components directory
  - directory: components
    # Title you would like to use
  - title: Components
